version: "3.8"

services:
  api:
    image: child_tracker_auth:latest
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    environment:
      CHILD_TRACKER_AUTH_HOST: 0.0.0.0
    volumes:
      - /home/docker/staff/data/var/www/vhosts/kidl/public/:/app/src/public/
      - /mnt/data/var/www/vhosts/kidl/public/:/app/src/mnt/public/
      - /tmp/child_tracker_auth_cache:/tmp/child_tracker_auth_cache
    network_mode: host
    dns:
      - 8.8.8.8
      - 8.8.4.4

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    environment:
      - REDIS_ARGS="--requirepass ${CHILD_TRACKER_AUTH_REDIS_PASSWORD}"
    network_mode: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
