services:
  mariadb-dev:
    image: docker.io/bitnami/mariadb:10.5.15
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - mariadb_data:/bitnami/mariadb
    env_file:
      - .env
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
  child_tracker_auth:
    build: .
    command: poetry run python app/app/main.py
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - MARIADB_HOST=mariadb-dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mariadb-dev
volumes:
  mariadb_data: