version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: child_tracker_auth:${CHILD_TRACKER_AUTH_VERSION:-latest}
    restart: always
    env_file:
      - .env.prod
    environment:
      CHILD_TRACKER_AUTH_HOST: 0.0.0.0
      CHILD_TRACKER_AUTH_DB_HOST: 10.88.0.3
      CHILD_TRACKER_AUTH_DB_PORT: 3306
    ports:
      - "8000:8000"
    volumes:
      - /home/docker/staff/data/var/www/vhosts/kidl/public/files:/app/src/public/files
    networks:
      - podman
networks:
  podman:
    external: true
