services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: child_tracker_auth:${CHILD_TRACKER_AUTH_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      CHILD_TRACKER_AUTH_HOST: 10.88.0.3
    ports:
      - "8000:8000"
