services:
  mysql:
    image: bitnami/mysql:8.4
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/bitnami/mysql/data
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  child_tracker_auth:
      build: ..
      command: python -m app
      restart: unless-stopped
      environment:
        - HOST=0.0.0.0
        - PORT=8000
        - DB_HOST=mysql
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        - mysql
volumes:
  mysql_data: